/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package solucao.de.banco;

import br.com.banco.Banco;
import br.com.banco.ContaCorrente;
import br.com.banco.GerenciadorDeClientes;
import br.com.pessoa.PessoaClienteFisica;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.JOptionPane;
import solucao.de.banco.TelaPrincipal;
import static solucao.de.banco.TelaPrincipal.banco;

/**
 *
 * @author Bruna
 */
public class Menu extends javax.swing.JInternalFrame{

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        jRBCorrente.setVisible(true);
        jRBPoupanca.setVisible(true);
        TelaPrincipal.jMenuItemInicio.setVisible(false);
        TelaPrincipal.jMenuItemADD.setVisible(false);
        
        
        
        /*Contas teste*/
        banco.clientes.adicionar("fisica", "tales", "rua a", "10359935621", new Date(), "mascu", "nulo", new Date(), "algo");
        banco.contas.adicionarCorrente("fisica", "tales", 1, 100, 1000, "123456");
        banco.clientes.adicionar("fisica", "tales 2", "rua a", "10359935621", new Date(), "mascu", "nulo", new Date(), "algo");
        banco.contas.adicionarCorrente("fisica", "tales 2", 2, 100, 1000, "1234562");
        
        /*importante*/
       TelaPrincipal.arquivo = "Menu";
       TelaPrincipal.jMenuItem2Voltar.setVisible(false);
       TelaPrincipal.jMenuItem2Sair.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtConta = new javax.swing.JTextField();
        btnEntrar = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();
        jRBFisica = new javax.swing.JRadioButton();
        jRBJuridica = new javax.swing.JRadioButton();
        jRBCorrente = new javax.swing.JRadioButton();
        jRBPoupanca = new javax.swing.JRadioButton();

        jLabel1.setText("Conta:");

        jLabel2.setText("Senha:");

        txtConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContaActionPerformed(evt);
            }
        });

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        jRBFisica.setText("Física");
        jRBFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBFisicaActionPerformed(evt);
            }
        });

        jRBJuridica.setText("Jurídica");
        jRBJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBJuridicaActionPerformed(evt);
            }
        });

        jRBCorrente.setText("Corrente");
        jRBCorrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCorrenteActionPerformed(evt);
            }
        });

        jRBPoupanca.setText("Poupança");
        jRBPoupanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBPoupancaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(207, 207, 207))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRBJuridica)
                                    .addComponent(jRBFisica))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRBPoupanca)
                                    .addComponent(jRBCorrente))
                                .addGap(69, 69, 69))
                            .addComponent(btnEntrar, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtConta, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBFisica)
                    .addComponent(jRBCorrente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBJuridica)
                    .addComponent(jRBPoupanca))
                .addGap(18, 18, 18)
                .addComponent(btnEntrar)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContaActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        if(!jRBCorrente.isSelected() && !jRBPoupanca.isSelected()){
            JOptionPane.showMessageDialog(null, "Preencha os campos corretamente!");
        }
        else{
            if(banco.clientes.validaCliente()){
                MenuCliente menuEntrar2 = new MenuCliente();
                TelaPrincipal.areaDesktop.add(menuEntrar2);

                menuEntrar2.setVisible(true);
                menuEntrar2.setSize(385,340);
                TelaPrincipal.areaDesktop.add(new MenuCliente());

                /**
                 * mostrar o botao de voltar e sair
                 */
                TelaPrincipal.jMenuItem2Voltar.setVisible(true);
                TelaPrincipal.jMenuItem2Sair.setVisible(true);
            }
            else
                JOptionPane.showMessageDialog(rootPane, "Conta incorreta!");
            }
        
        
        
        /*
        
        */
        
        /*
        MenuCliente menuc = new MenuCliente();
        telap.areaDesktop.add(menuc);
        menuc.setVisible(true);*/
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void jRBFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBFisicaActionPerformed
        jRBJuridica.setSelected(false);
        jRBPoupanca.setVisible(true);
    }//GEN-LAST:event_jRBFisicaActionPerformed

    private void jRBJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBJuridicaActionPerformed
        jRBFisica.setSelected(false);
        jRBPoupanca.setSelected(false);
        jRBPoupanca.setVisible(false);
    }//GEN-LAST:event_jRBJuridicaActionPerformed

    private void jRBCorrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCorrenteActionPerformed
        jRBPoupanca.setSelected(false);
    }//GEN-LAST:event_jRBCorrenteActionPerformed

    private void jRBPoupancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBPoupancaActionPerformed
        jRBCorrente.setSelected(false);
    }//GEN-LAST:event_jRBPoupancaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JRadioButton jRBCorrente;
    public static javax.swing.JRadioButton jRBFisica;
    public static javax.swing.JRadioButton jRBJuridica;
    public static javax.swing.JRadioButton jRBPoupanca;
    public static javax.swing.JTextField txtConta;
    public static javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
