/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package solucao.de.banco;

import static solucao.de.banco.TelaPrincipal.banco;

/**
 *
 * @author Bruna
 */
public class Saldo extends javax.swing.JInternalFrame {

    /**
     * Creates new form Saldo
     */
    public Saldo() {
        initComponents();
        exibir();
        TelaPrincipal.arquivo = "Saldo";
    }
    
    private void exibir(){
        if(TelaPrincipal.tipoCliente.equals("Fisica") && TelaPrincipal.tipoConta.equals("Conta Corrente")){
           
            jTFexibeSaldoDisp.setVisible(true);
            jLabel2.setVisible(true);
            
            this.jTFexibeSaldo.setText(String.valueOf(banco.clientes.listaClienteFi.get(TelaPrincipal.pCliente).listaCC.get(TelaPrincipal.pConta).getSaldo()));
            jTFexibeSaldoDisp.setText(String.valueOf(banco.clientes.listaClienteFi.get(TelaPrincipal.pCliente).listaCC.get(TelaPrincipal.pConta).getSaldoLimite()));
            
            
        }
        else if(TelaPrincipal.tipoCliente.equals("Fisica") && TelaPrincipal.tipoConta.equals("Conta Poupança")){
            this.jTFexibeSaldo.setText(String.valueOf(banco.clientes.listaClienteFi.get(TelaPrincipal.pCliente).listaCP.get(TelaPrincipal.pConta).getSaldo()));
            
            /*poupança nao tem limite*/
            jTFexibeSaldoDisp.setVisible(false);
            jLabel2.setVisible(false);
        }
        else if(TelaPrincipal.tipoCliente.equals("Juridica") && TelaPrincipal.tipoConta.equals("Conta Corrente")){
            
            jTFexibeSaldoDisp.setVisible(true);
            jLabel2.setVisible(true);
            
            this.jTFexibeSaldo.setText(String.valueOf(banco.clientes.listaClienteJu.get(TelaPrincipal.pCliente).listaCC.get(TelaPrincipal.pConta).getSaldo()));
            jTFexibeSaldoDisp.setText(String.valueOf(banco.clientes.listaClienteJu.get(TelaPrincipal.pCliente).listaCC.get(TelaPrincipal.pConta).getSaldoLimite()));
        }
    }

    
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        lblLimite = new javax.swing.JLabel();
        painelPoupanca = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblRendimento = new javax.swing.JLabel();
        jTFrendimento = new javax.swing.JTextField();
        jTFexibeSaldo = new javax.swing.JTextField();
        jTFexibeSaldoDisp = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Saldo Conta:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Saldo Disponível:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Rendimento:");

        javax.swing.GroupLayout painelPoupancaLayout = new javax.swing.GroupLayout(painelPoupanca);
        painelPoupanca.setLayout(painelPoupancaLayout);
        painelPoupancaLayout.setHorizontalGroup(
            painelPoupancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPoupancaLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jTFrendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelPoupancaLayout.setVerticalGroup(
            painelPoupancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPoupancaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPoupancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelPoupancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTFrendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
        );

        jTFexibeSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFexibeSaldoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelPoupanca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFexibeSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jTFexibeSaldoDisp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(lblLimite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTFexibeSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTFexibeSaldoDisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelPoupanca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFexibeSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFexibeSaldoActionPerformed
        
    }//GEN-LAST:event_jTFexibeSaldoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTFexibeSaldo;
    private javax.swing.JTextField jTFexibeSaldoDisp;
    private javax.swing.JTextField jTFrendimento;
    private javax.swing.JLabel lblLimite;
    private javax.swing.JLabel lblRendimento;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JPanel painelPoupanca;
    // End of variables declaration//GEN-END:variables
}
