/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package solucao.de.banco;

import br.com.banco.Banco;
import br.com.banco.GerenciadorDeClientes;
import br.com.banco.GerenciadorDeContas;
import javax.swing.JOptionPane;

/**
 * Tales Sathler
   Bruna Cristine
   Thiago Nascimento
   Victor Trevenzoli
   Hericlis Martins
 */


/**
 *
 * @author Bruna
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
        
        Menu menuEntrar = new Menu();
        areaDesktop.add(menuEntrar);
        menuEntrar.setVisible(true);
        menuEntrar.setSize(385,340);
        
        AddNovaConta.setVisible(true);
        jMenuItemInicio.setVisible(true);
        jMenuItemADD.setVisible(true);
    }
    
    //PessoaClienteFisica pf = new PessoaClienteFisica(null, null, null, null, null, null)
    static GerenciadorDeClientes gcli = new GerenciadorDeClientes();
    static GerenciadorDeContas gcon = new GerenciadorDeContas(gcli);
    static Banco banco = new Banco("Brasil", "Rua A", gcli, gcon);
    
    //sessao do usuario logado
    public static String tipoCliente;
    public static String tipoConta;
    public static int pCliente;
    public static int pConta;
    
    /**
     * para indicar qual tela esta
     */
    public static String arquivo;
    
    
    public static void verificaJanelas(){
        if(areaDesktop.getSelectedFrame().isVisible()){
            areaDesktop.getAllFrames().equals(false);
        }
    }
    
    public static void inicio(){
        Menu menuEntrar = new Menu();
        areaDesktop.add(menuEntrar);
        menuEntrar.setVisible(true);
        menuEntrar.setSize(385,340);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areaDesktop = new javax.swing.JDesktopPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        AddNovaConta = new javax.swing.JMenu();
        jMenuItemInicio = new javax.swing.JMenuItem();
        jMenuItemADD = new javax.swing.JMenuItem();
        jMenuItem2Voltar = new javax.swing.JMenuItem();
        jMenuItem2Sair = new javax.swing.JMenuItem();
        menuInfo = new javax.swing.JMenu();
        menuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout areaDesktopLayout = new javax.swing.GroupLayout(areaDesktop);
        areaDesktop.setLayout(areaDesktopLayout);
        areaDesktopLayout.setHorizontalGroup(
            areaDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, areaDesktopLayout.createSequentialGroup()
                .addGap(0, 300, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        areaDesktopLayout.setVerticalGroup(
            areaDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaDesktopLayout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 174, Short.MAX_VALUE))
        );
        areaDesktop.setLayer(jDesktopPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        AddNovaConta.setText("Opções");
        AddNovaConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNovaContaActionPerformed(evt);
            }
        });

        jMenuItemInicio.setText("Início");
        jMenuItemInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInicioActionPerformed(evt);
            }
        });
        AddNovaConta.add(jMenuItemInicio);

        jMenuItemADD.setText("Adicionar nova conta");
        jMenuItemADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemADDActionPerformed(evt);
            }
        });
        AddNovaConta.add(jMenuItemADD);

        jMenuItem2Voltar.setText("Voltar");
        jMenuItem2Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2VoltarActionPerformed(evt);
            }
        });
        AddNovaConta.add(jMenuItem2Voltar);

        jMenuItem2Sair.setText("Sair");
        jMenuItem2Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2SairActionPerformed(evt);
            }
        });
        AddNovaConta.add(jMenuItem2Sair);

        jMenuBar1.add(AddNovaConta);

        menuInfo.setText("Info");

        menuSobre.setText("Sobre");
        menuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSobreActionPerformed(evt);
            }
        });
        menuInfo.add(menuSobre);

        jMenuBar1.add(menuInfo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaDesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSobreActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Banco MoneyOn ...\nDireitos Reservados");
    }//GEN-LAST:event_menuSobreActionPerformed

    private void jMenuItemADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemADDActionPerformed
        String op = JOptionPane.showInputDialog(rootPane, "Digite Fisica ou Juridica");
            
        /**
         * verifica qual tipo de cadastro
         */
        if(op.equals("Fisica") || op.equals("fisica")){
            NovaContaFisica contapf = new NovaContaFisica();
            TelaPrincipal.areaDesktop.add(contapf);

            contapf.setVisible(true);
            contapf.setSize(385,340);
            TelaPrincipal.areaDesktop.add(new NovaContaFisica());
        }
        else if(op.equals("Juridica") || op.equals("juridica") || op.equals("Jurídica") || op.equals("jurídica")){
            NovaContaJuridica contapj = new NovaContaJuridica();
            TelaPrincipal.areaDesktop.add(contapj);

            contapj.setVisible(true);
            contapj.setSize(385,340);
            TelaPrincipal.areaDesktop.add(new NovaContaJuridica());
        }
    }//GEN-LAST:event_jMenuItemADDActionPerformed

    private void AddNovaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNovaContaActionPerformed
        //verificaJanelas();
        
            NovaContaFisica contapf = new NovaContaFisica();
            TelaPrincipal.areaDesktop.add(contapf);

            contapf.setVisible(true);
            contapf.setSize(385,340);
            TelaPrincipal.areaDesktop.add(new NovaContaFisica());
        
    }//GEN-LAST:event_AddNovaContaActionPerformed

    private void jMenuItem2VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2VoltarActionPerformed
        if(TelaPrincipal.arquivo.equals("Depositar") || TelaPrincipal.arquivo.equals("Transferir") || 
                TelaPrincipal.arquivo.equals("Sacar") || TelaPrincipal.arquivo.equals("Saldo")){
            
            MenuCliente menuEntrar2 = new MenuCliente();
            TelaPrincipal.areaDesktop.add(menuEntrar2);

            menuEntrar2.setVisible(true);
            menuEntrar2.setSize(385,340);
            TelaPrincipal.areaDesktop.add(new MenuCliente());
        }
    }//GEN-LAST:event_jMenuItem2VoltarActionPerformed

    private void jMenuItem2SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2SairActionPerformed
        TelaPrincipal.tipoConta = null;
        TelaPrincipal.tipoCliente = null;
        TelaPrincipal.pConta = -1;
        TelaPrincipal.pCliente = -1;
        areaDesktop.removeAll();
        Menu menuEntrar = new Menu();
        areaDesktop.add(menuEntrar);
        menuEntrar.setVisible(true);
        menuEntrar.setSize(385,340);
        
        TelaPrincipal.jMenuItemInicio.setVisible(true);
        TelaPrincipal.jMenuItemADD.setVisible(true);
    }//GEN-LAST:event_jMenuItem2SairActionPerformed

    private void jMenuItemInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInicioActionPerformed
        
        Menu menuEntrar = new Menu();
        areaDesktop.add(menuEntrar);
        menuEntrar.setVisible(true);
        menuEntrar.setSize(385,340);
        
        TelaPrincipal.jMenuItemInicio.setVisible(true);
        TelaPrincipal.jMenuItemADD.setVisible(true);
    }//GEN-LAST:event_jMenuItemInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            //new TelaPrincipal().setVisible(true);
            TelaPrincipal principal = new TelaPrincipal();
            principal.setSize(400,400);
            principal.setVisible(true);
            principal.setLocationRelativeTo(null);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AddNovaConta;
    public static javax.swing.JDesktopPane areaDesktop;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JMenuItem jMenuItem2Sair;
    public static javax.swing.JMenuItem jMenuItem2Voltar;
    public static javax.swing.JMenuItem jMenuItemADD;
    public static javax.swing.JMenuItem jMenuItemInicio;
    private javax.swing.JMenu menuInfo;
    private javax.swing.JMenuItem menuSobre;
    // End of variables declaration//GEN-END:variables
}
