/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package solucao.de.banco;

import javax.swing.JOptionPane;
import static solucao.de.banco.TelaPrincipal.banco;

/**
 *
 * @author Bruna
 */
public class Transferir extends javax.swing.JInternalFrame {

    /**
     * Creates new form Transferir
     */
    public Transferir() {
        initComponents();
        TelaPrincipal.arquivo = "Transferir";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNumeroConta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTipoConta = new javax.swing.JComboBox();
        btnTransferir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtValorTransferencia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTipoCliente = new javax.swing.JComboBox();

        jLabel1.setText("Número da Conta:");

        jLabel2.setText("Tipo de Conta:");

        jTipoConta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Conta Corrente", "Conta Poupança" }));

        btnTransferir.setText("Transferir");
        btnTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferirActionPerformed(evt);
            }
        });

        jLabel3.setText("Valor a ser transferido:");

        jLabel4.setText("Tipo de Cliente");

        jTipoCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fisica", "Juridica" }));
        jTipoCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jTipoClienteItemStateChanged(evt);
            }
        });
        jTipoCliente.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jTipoClienteHierarchyChanged(evt);
            }
        });
        jTipoCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTipoClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTipoClienteFocusLost(evt);
            }
        });
        jTipoCliente.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jTipoClientePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jTipoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTipoClienteMouseClicked(evt);
            }
        });
        jTipoCliente.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jTipoClienteComponentHidden(evt);
            }
        });
        jTipoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTipoClienteActionPerformed(evt);
            }
        });
        jTipoCliente.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTipoClientePropertyChange(evt);
            }
        });
        jTipoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTipoClienteKeyPressed(evt);
            }
        });
        jTipoCliente.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jTipoClienteVetoableChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNumeroConta)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTipoConta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTipoCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtValorTransferencia))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTransferir)))
                .addGap(59, 59, 59))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jTipoCliente, jTipoConta, txtNumeroConta, txtValorTransferencia});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtValorTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnTransferir)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jTipoCliente, jTipoConta, txtNumeroConta, txtValorTransferencia});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirActionPerformed
       System.out.println("Tipo cliente: "+TelaPrincipal.tipoCliente+TelaPrincipal.pCliente);
       System.out.println("Tipo conta: "+TelaPrincipal.tipoConta+TelaPrincipal.pConta);
        
       //verifica se vai transferir para uma conta fisica ou juridica
       if(jTipoCliente.getSelectedItem().equals("Fisica")){
           JOptionPane.showMessageDialog(null, "para conta fisica");
           //verifica se vai transferir para uma conta corrente ou poupanca
            if(jTipoConta.getSelectedItem().equals("Conta Corrente")){
                JOptionPane.showMessageDialog(null, "para conta corrente");
                banco.clientes.transCliF("Conta Corrente", Integer.valueOf(txtNumeroConta.getText()), Double.valueOf(txtValorTransferencia.getText()));
            }
            else{
                banco.clientes.transCliF("Conta Poupança", Integer.valueOf(txtNumeroConta.getText()), Double.valueOf(txtValorTransferencia.getText()));
            }
       }
       else{
           JOptionPane.showMessageDialog(null, "para conta juridica");
           if(jTipoConta.getSelectedItem().equals("Conta Corrente")){
               JOptionPane.showMessageDialog(null, "para conta corrente");
                banco.clientes.transCliJ("Conta Corrente", Integer.valueOf(txtNumeroConta.getText()), Double.valueOf(txtValorTransferencia.getText()));
           }
           else
               banco.clientes.transCliJ("Conta Poupança", Integer.valueOf(txtNumeroConta.getText()), Double.valueOf(txtValorTransferencia.getText()));
       }
       
    }//GEN-LAST:event_btnTransferirActionPerformed

    private void jTipoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTipoClienteActionPerformed
        if(jTipoCliente.getSelectedItem().equals("Juridica")){
            jTipoConta.setVisible(false);
            jLabel2.setVisible(false);
        }
        else{
            jTipoConta.setVisible(true);
            jLabel2.setVisible(true);
        }
    }//GEN-LAST:event_jTipoClienteActionPerformed

    private void jTipoClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jTipoClienteItemStateChanged
        //JOptionPane.showMessageDialog(null, jTipoCliente.getSelectedItem().equals("Juridica"));
        /*
        if(jTipoCliente.getSelectedItem().equals("Juridica")){
            jTipoConta.setVisible(false);
            jLabel2.setVisible(false);
        }
        else{
            jTipoConta.setVisible(true);
            jLabel2.setVisible(true);
        }*/
    }//GEN-LAST:event_jTipoClienteItemStateChanged

    private void jTipoClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTipoClienteMouseClicked
        
    }//GEN-LAST:event_jTipoClienteMouseClicked

    private void jTipoClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTipoClienteFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTipoClienteFocusGained

    private void jTipoClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTipoClienteFocusLost
        
    }//GEN-LAST:event_jTipoClienteFocusLost

    private void jTipoClientePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jTipoClientePopupMenuWillBecomeInvisible
        
    }//GEN-LAST:event_jTipoClientePopupMenuWillBecomeInvisible

    private void jTipoClientePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTipoClientePropertyChange
        
    }//GEN-LAST:event_jTipoClientePropertyChange

    private void jTipoClienteHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jTipoClienteHierarchyChanged
        
    }//GEN-LAST:event_jTipoClienteHierarchyChanged

    private void jTipoClienteComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTipoClienteComponentHidden
        
    }//GEN-LAST:event_jTipoClienteComponentHidden

    private void jTipoClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTipoClienteKeyPressed
        
    }//GEN-LAST:event_jTipoClienteKeyPressed

    private void jTipoClienteVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jTipoClienteVetoableChange
        
    }//GEN-LAST:event_jTipoClienteVetoableChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTransferir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox jTipoCliente;
    private javax.swing.JComboBox jTipoConta;
    private javax.swing.JTextField txtNumeroConta;
    private javax.swing.JTextField txtValorTransferencia;
    // End of variables declaration//GEN-END:variables
}
